server:
  port: 8080

ledgerly:
  security:
    enabled: ${LEDGERLY_SECURITY_ENABLED:false}
  kafka:
    topics:
      sagaCommands: ${LEDGERLY_KAFKA_TOPICS_SAGACOMMANDS:ledgerly.saga.commands}
      domainEvents: ${LEDGERLY_KAFKA_TOPICS_DOMAINEVENTS:ledgerly.domain.events}
      auditEvents: ${LEDGERLY_KAFKA_TOPICS_AUDITEVENTS:ledgerly.audit.events}
  masterpass:
    baseUrl: ${LEDGERLY_MASTERPASS_BASEURL:http://masterpass-mock}
    bearerToken: ${LEDGERLY_MASTERPASS_BEARERTOKEN:FIXED_DEMO_TOKEN}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
