apiVersion: v1
kind: Secret
metadata:
  name: ledgerly-db-secret
  namespace: ledgerly
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/ledgerly"
  SPRING_DATASOURCE_USERNAME: "ledgerly"
  SPRING_DATASOURCE_PASSWORD: "ledgerly"
