apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ledgerly
  namespace: ledgerly
spec:
  rules:
    - host: ledgerly.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ledgerly-app
                port:
                  number: 80
